modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/JuiceyBeans/Slugmo/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/JuiceyBeans/Slugmo"
logoFile="icon.png"
credits="GregTech CEu Modern developers, Friendship & Love Club, TheOnlyRosalyn"
authors = "${mod_authors}"
displayTest="MATCH_VERSION"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "geckolib"
mandatory = true
versionRange = "${geckolib_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
